routes/web.php
<?php
use App\Models\DataType;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::group(['prefix' => 'admin'], function () {
//    Voyager::routes();
    Route::get('test', function () {
       return 'Hello World';
    });
    Route::group(['as' => 'voyager.'], function () {
//        event('voyager.routing', app('router'));

//        $namespacePrefix = '\\'.config('voyager.controllers.namespace').'\\';

        Route::get('login', ['uses' => 'VoyagerAuthController@login', 'as' => 'login']);
        Route::post('login', ['uses' => 'VoyagerAuthController@postLogin', 'as' => 'postlogin']);

        Route::group(['middleware' => 'admin.user'], function () {
            event('voyager.admin.routing', app('router'));

            // Main Admin and Logout Route
            Route::get('/', ['uses' => 'VoyagerController@index', 'as' => 'dashboard']);
            Route::post('logout', ['uses' => 'VoyagerController@logout', 'as' => 'logout']);
            Route::post('upload', ['uses' => 'VoyagerController@upload', 'as' => 'upload']);

            Route::get('profile', ['uses' => 'VoyagerController@profile', 'as' => 'profile']);

            try {
                foreach (DataType::all() as $dataType) {
                    $breadController = $dataType->controller
                        ? $dataType->controller
                        : 'VoyagerBreadController';

                    Route::resource($dataType->slug, $breadController);
                }
            } catch (\InvalidArgumentException $e) {
                throw new \InvalidArgumentException("Custom routes hasn't been configured because: ".$e->getMessage(), 1);
            } catch (\Exception $e) {
                // do nothing, might just be because table not yet migrated.
            }

            // Role Routes
            Route::resource('roles', 'VoyagerRoleController');

            // Menu Routes
            Route::group([
                'as'     => 'menus.',
                'prefix' => 'menus/{menu}',
            ], function () {
                Route::get('builder', ['uses' => 'VoyagerMenuController@builder', 'as' => 'builder']);
                Route::post('order', ['uses' => 'VoyagerMenuController@order_item', 'as' => 'order']);

                Route::group([
                    'as'     => 'item.',
                    'prefix' => 'item',
                ], function () {
                    Route::delete('{id}', ['uses' => 'VoyagerMenuController@delete_menu', 'as' => 'destroy']);
                    Route::post('/', ['uses' => 'VoyagerMenuController@add_item', 'as' => 'add']);
                    Route::put('/', ['uses' => 'VoyagerMenuController@update_item', 'as' => 'update']);
                });
            });

            // Settings
            Route::group([
                'as'     => 'settings.',
                'prefix' => 'settings',
            ], function () {
                Route::get('/', ['uses' => 'VoyagerSettingsController@index', 'as' => 'index']);
                Route::post('/', ['uses' => 'VoyagerSettingsController@store', 'as' => 'store']);
                Route::put('/', ['uses' => 'VoyagerSettingsController@update', 'as' => 'update']);
                Route::delete('{id}', ['uses' => 'VoyagerSettingsController@delete', 'as' => 'delete']);
                Route::get('{id}/move_up', ['uses' => 'VoyagerSettingsController@move_up', 'as' => 'move_up']);
                Route::get('{id}/move_down', ['uses' => 'VoyagerSettingsController@move_down', 'as' => 'move_down']);
                Route::get('{id}/delete_value', ['uses' => 'VoyagerSettingsController@delete_value', 'as' => 'delete_value']);
            });

            // Admin Media
            Route::group([
                'as'     => 'media.',
                'prefix' => 'media',
            ], function () {
                Route::get('/', ['uses' => 'VoyagerMediaController@index', 'as' => 'index']);
                Route::post('files', ['uses' => 'VoyagerMediaController@files', 'as' => 'files']);
                Route::post('new_folder', ['uses' => 'VoyagerMediaController@new_folder', 'as' => 'new_folder']);
                Route::post('delete_file_folder', ['uses' => 'VoyagerMediaController@delete_file_folder', 'as' => 'delete_file_folder']);
                Route::post('directories', ['uses' => 'VoyagerMediaController@get_all_dirs', 'as' => 'get_all_dirs']);
                Route::post('move_file', ['uses' => 'VoyagerMediaController@move_file', 'as' => 'move_file']);
                Route::post('rename_file', ['uses' => 'VoyagerMediaController@rename_file', 'as' => 'rename_file']);
                Route::post('upload', ['uses' => 'VoyagerMediaController@upload', 'as' => 'upload']);
                Route::post('remove', ['uses' => 'VoyagerMediaController@remove', 'as' => 'remove']);
            });

            // Database Routes
            Route::group([
                'as'     => 'database.',
                'prefix' => 'database',
            ], function () {
                Route::get('bread/{table}/create', ['uses' => 'VoyagerDatabaseController@addBread', 'as' => 'create_bread']);
                Route::post('bread/', ['uses' => 'VoyagerDatabaseController@storeBread', 'as' => 'store_bread']);
                Route::get('bread/{table}/edit', ['uses' => 'VoyagerDatabaseController@addEditBread', 'as' => 'edit_bread']);
                Route::put('bread/{id}', ['uses' => 'VoyagerDatabaseController@updateBread', 'as' => 'update_bread']);
                Route::delete('bread/{id}', ['uses' => 'VoyagerDatabaseController@deleteBread', 'as' => 'delete_bread']);
            });

            Route::resource('database', 'VoyagerDatabaseController');
        });
    });
});

resources/views/dashboard/navbar.blade.php
<nav class="navbar navbar-default navbar-fixed-top navbar-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button class="hamburger btn-link">
                <span class="hamburger-inner"></span>
            </button>
            <a id="sidebar-anchor" class="voyager-anchor btn-link navbar-link hidden-xs" 
                title="Yarr! Drop the anchors! (and keep the sidebar open)" 
                data-unstick="Unstick the sidebar" 
            data-toggle="tooltip" data-placement="bottom"></a>

            <ol class="breadcrumb hidden-xs">
                @if(count(Request::segments()) == 1)
                    <li class="active"><i class="voyager-boat"></i> Dashboard</li>
                @else
                    <li class="active">
                        <a href="{{ route('voyager.dashboard')}}"><i class="voyager-boat"></i> Dashboard</a>
                    </li>
                @endif
                <?php $breadcrumb_url = ''; ?>
                @for($i = 1; $i <= count(Request::segments()); $i++)
                    <?php $breadcrumb_url .= '/' . Request::segment($i); ?>
                    @if(Request::segment($i) != ltrim(route('voyager.dashboard', [], false), '/') && !is_numeric(Request::segment($i)))

                        @if($i < count(Request::segments()) & $i > 0)
                            <li class="active"><a
                                        href="{{ $breadcrumb_url }}">{{ ucwords(str_replace('-', ' ', str_replace('_', ' ', Request::segment($i)))) }}</a>
                            </li>
                        @else
                            <li>{{ ucwords(str_replace('-', ' ', str_replace('_', ' ', Request::segment($i)))) }}</li>
                        @endif

                    @endif
                @endfor
            </ol>
        </div>
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown profile">
                <a href="#" class="dropdown-toggle text-right" data-toggle="dropdown" role="button"
                   aria-expanded="false"><img src="{{ $user_avatar }}" class="profile-img"> <span
                            class="caret"></span></a>
                <ul class="dropdown-menu dropdown-menu-animated">
                    <li class="profile-img">
                        <img src="{{ $user_avatar }}" class="profile-img">
                        <div class="profile-body">
                            <h5>{{ Auth::user()->name }}</h5>
                            <h6>{{ Auth::user()->email }}</h6>
                        </div>
                    </li>
                    <li class="divider"></li>
                    <?php $nav_items = config('voyager.dashboard.navbar_items'); ?>
                    @if(is_array($nav_items) && !empty($nav_items))
                    @foreach($nav_items as $name => $item)
                    <li {!! isset($item['classes']) && !empty($item['classes']) ? 'class="'.$item['classes'].'"' : '' !!}>
                        @if(isset($item['route']) && $item['route'] == 'voyager.logout')
                        <form action="{{ route('voyager.logout') }}" method="POST">
                            {{ csrf_field() }}
                            <button type="submit" class="btn btn-danger btn-block">
                                @if(isset($item['icon_class']) && !empty($item['icon_class']))
                                <i class="{!! $item['icon_class'] !!}"></i>
                                @endif
                                {{$name}}
                            </button>
                        </form>
                        @else
                        <a href="{{ isset($item['route']) && Route::has($item['route']) ? route($item['route']) : (isset($item['route']) ? $item['route'] : '#') }}" {!! isset($item['target_blank']) && $item['target_blank'] ? 'target="_blank"' : '' !!}>
                            @if(isset($item['icon_class']) && !empty($item['icon_class']))
                            <i class="{!! $item['icon_class'] !!}"></i>
                            @endif
                            {{$name}}
                        </a>
                        @endif
                    </li>
                    @endforeach
                    @endif
                </ul>
            </li>
        </ul>
    </div>
</nav>

resources/views/dashboard/sidebar.blade.php
<div class="side-menu sidebar-inverse">
    <nav class="navbar navbar-default" role="navigation">
        <div class="side-menu-container">
            <div class="navbar-header">
                <a class="navbar-brand" href="{{ route('voyager.dashboard') }}">
                    <div class="logo-icon-container">
                        <?php $admin_logo_img = Voyager::setting('admin_icon_image', ''); ?>
                        @if($admin_logo_img == '')
                            <img src="{{ voyager_asset('images/logo-icon-light.png') }}" alt="Logo Icon">
                        @else
                            <img src="{{ Voyager::image($admin_logo_img) }}" alt="Logo Icon">
                        @endif
                    </div>
                    <div class="title">{{Voyager::setting('admin_title', 'VOYAGER')}}</div>
                </a>
            </div><!-- .navbar-header -->

            <div class="panel widget center bgimage"
                 style="background-image:url({{ Voyager::image( Voyager::setting('admin_bg_image'), config('voyager.assets_path') . '/images/bg.jpg' ) }});">
                <div class="dimmer"></div>
                <div class="panel-content">
                    <img src="{{ $user_avatar }}" class="avatar" alt="{{ Auth::user()->name }} avatar">
                    <h4>{{ ucwords(Auth::user()->name) }}</h4>
                    <p>{{ Auth::user()->email }}</p>

                    <a href="{{ route('voyager.profile') }}" class="btn btn-primary">Profile</a>
                    <div style="clear:both"></div>
                </div>
            </div>

        </div>

        {!! menu('admin', 'admin_menu') !!}
    </nav>
</div>